_commit: v0.4.61
_src_path: git@github.com:tschm/package.git
description: Collection of tools to generate alpha on your given portfolios
gh_create: gh repo create armaanPy/alphastack --public --description 'Collection of
  tools to generate alpha on your given portfolios'
page: https://armaanPy.github.io/alphastack
project_name: alphastack
repository: https://github.com/armaanPy/alphastack
ssh_uri: git@github.com:armaanPy/alphastack.git
status: public
username: armaanPy
